# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quail_db_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # 루트 비밀번호 (개발용)
      MYSQL_DATABASE: quail_db   # 생성할 DB 이름
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # 내 컴퓨터 3306 포트와 연결
    volumes:
      - ./db_data:/var/lib/mysql # 데이터를 내 컴퓨터 폴더에 저장 (꺼도 안 날아감)